# Change baseurl before deploy
baseurl = "https://anemele.github.io/blog"
title = "Jason Swift's blogs"
languageCode = "en-us"
theme = "stack"

pagination.pagerSize = 5

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

# do not know what these settings do
[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", "date"]

# Set the RSS name
# See: https://github.com/CaiJimmy/hugo-theme-stack/issues/376#issuecomment-940739651
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"
